"""initial MySQL schema

Revision ID: 5c4e394deca5
Revises: 
Create Date: 2026-09-23 19:19:00.291218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database import Geometry
from app.database import UTCDateTime

# Tables whose rows may only ever be added, never changed or removed. Each gets a BEFORE UPDATE
# and a BEFORE DELETE trigger below.
#
# MySQL cannot go further than that on its own. Unlike PostgreSQL there is no BEFORE TRUNCATE
# trigger - TRUNCATE does not fire triggers at all and empties the table with no error (verified
# on MySQL 8.0.46). What closes that hole is the privilege system: TRUNCATE needs the DROP
# privilege, and the application account is never granted it. See app/db/harden.py, which must
# be run after this migration.
APPEND_ONLY_TABLES = (
    "audit_log",
    "chain_of_custody_entries",
    "station_diary_entries",
    "case_diary_entries",
)

# Only NOT NULL geometry columns can carry a spatial index in MySQL, which excludes
# police_stations.location (a station may have no mapped location yet).
SPATIAL_INDEXES = (
    ("sp_wards_boundary", "wards", "boundary"),
    ("sp_infrastructure_issues_location", "infrastructure_issues", "location"),
    ("sp_violation_cases_location", "violation_cases", "location"),
)

revision: str = '5c4e394deca5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('VIEW', 'CONFIRM', 'RECLASSIFY', 'DISMISS', 'UNBLUR_TOGGLE', 'CHALLAN_ISSUED', 'STATUS_CHANGE', 'LOGIN', 'GRIEVANCE_DECISION', 'TAKEDOWN', 'REPLY_PUBLISHED', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_table('corruption_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('accused_department', sa.String(length=255), nullable=False),
    sa.Column('accused_designation', sa.String(length=255), nullable=False),
    sa.Column('accused_party_type', sa.Enum('STATE_GOVT_EMPLOYEE', 'CENTRAL_GOVT_EMPLOYEE', 'POLICE_PERSONNEL', 'MUNICIPAL_OR_DEPT_STAFF', name='corruption_accused_party_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geohash', sa.String(length=20), nullable=False),
    sa.Column('media_id', sa.String(length=255), nullable=False),
    sa.Column('moderation_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='moderation_status'), nullable=False),
    sa.Column('public_status_badge', sa.Enum('UNVERIFIED_ALLEGATION', 'UNDER_INVESTIGATION', 'ACTION_TAKEN', 'DISMISSED', name='public_status_badge'), nullable=False),
    sa.Column('tracking_token', sa.String(length=64), nullable=False),
    sa.Column('taken_down_at', UTCDateTime(), nullable=True),
    sa.Column('takedown_reason', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corruption_reports_tracking_token'), 'corruption_reports', ['tracking_token'], unique=True)
    op.create_table('corruption_routing_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('accused_party_type', sa.Enum('STATE_GOVT_EMPLOYEE', 'CENTRAL_GOVT_EMPLOYEE', 'POLICE_PERSONNEL', 'MUNICIPAL_OR_DEPT_STAFF', name='accused_party_type'), nullable=False),
    sa.Column('primary_route_body', sa.String(length=255), nullable=False),
    sa.Column('notify_local_police', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accused_party_type')
    )
    op.create_table('emergency_routing_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('ASSAULT_IN_PROGRESS', 'HOMICIDE_OR_BODY_DISCOVERED', 'SEXUAL_OFFENCE_ADULT', 'MINOR_INVOLVED', 'NARCOTICS', 'HUMAN_TRAFFICKING', name='offence_category'), nullable=False),
    sa.Column('alert_routed_to', sa.String(length=500), nullable=False),
    sa.Column('has_public_record', sa.Boolean(), nullable=False),
    sa.Column('is_hard_stop', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('issue_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('escalation_department', sa.String(length=255), nullable=False),
    sa.Column('escalation_department_tier2', sa.String(length=255), nullable=True),
    sa.Column('duplicate_radius_meters', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('issue_contact_phones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_token', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_contact_phones_contact_token'), 'issue_contact_phones', ['contact_token'], unique=True)
    op.create_table('police_stations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('ward_id', sa.Uuid(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('location', Geometry('POINT', 4326), nullable=True),
    sa.Column('sho_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('responsible_desks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('ward_id', sa.Uuid(), nullable=True),
    sa.Column('municipal_zone', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('grievance_api_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synthetic_vehicle_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthetic_vehicle_registry_plate_number'), 'synthetic_vehicle_registry', ['plate_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MUNICIPAL_OFFICER', 'VIGILANCE_OFFICER', 'MODERATOR', 'DEPARTMENT_ENGINEER', 'INVESTIGATING_OFFICER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('jurisdiction_ward_id', sa.Uuid(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('police_station_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('violation_class_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('identity_path', sa.Enum('ANPR', 'UNIDENTIFIED', name='identity_path'), nullable=False),
    sa.Column('statutory_section', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('wards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ward_number', sa.String(length=50), nullable=False),
    sa.Column('municipal_zone', sa.String(length=255), nullable=False),
    sa.Column('assembly_constituency', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('boundary', Geometry('POLYGON', 4326), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_grievances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket', sa.String(length=20), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('ground', sa.Enum('FACTUALLY_INCORRECT', 'IDENTIFIES_PRIVATE_PERSON', 'DEFAMATORY', 'SUB_JUDICE', 'NOT_MY_DEPARTMENT', 'OTHER', name='grievance_ground'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('complainant_name', sa.String(length=255), nullable=False),
    sa.Column('complainant_email', sa.String(length=320), nullable=False),
    sa.Column('complainant_designation', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'ACKNOWLEDGED', 'UPHELD', 'REJECTED', name='grievance_status'), nullable=False),
    sa.Column('received_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', UTCDateTime(), nullable=True),
    sa.Column('resolved_at', UTCDateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['corruption_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_grievances_report_id'), 'content_grievances', ['report_id'], unique=False)
    op.create_index(op.f('ix_content_grievances_ticket'), 'content_grievances', ['ticket'], unique=True)
    op.create_table('emergency_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('ASSAULT_IN_PROGRESS', 'HOMICIDE_OR_BODY_DISCOVERED', 'SEXUAL_OFFENCE_ADULT', 'MINOR_INVOLVED', 'NARCOTICS', 'HUMAN_TRAFFICKING', name='emergency_report_category'), nullable=False),
    sa.Column('original_sha256', sa.String(length=64), nullable=True),
    sa.Column('media_id', sa.String(length=255), nullable=True),
    sa.Column('geohash', sa.String(length=20), nullable=False),
    sa.Column('ward_id', sa.Uuid(), nullable=True),
    sa.Column('station_id', sa.Uuid(), nullable=True),
    sa.Column('tracking_token', sa.String(length=64), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', UTCDateTime(), nullable=True),
    sa.Column('closed_without_fir_reason', sa.String(length=500), nullable=True),
    sa.Column('closed_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['police_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_reports_tracking_token'), 'emergency_reports', ['tracking_token'], unique=True)
    op.create_table('fine_ladder_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('violation_class_id', sa.Uuid(), nullable=False),
    sa.Column('occurrence_number', sa.Integer(), nullable=False),
    sa.Column('amount_rupees', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['violation_class_id'], ['violation_class_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', Geometry('POINT', 4326), nullable=False),
    sa.Column('ward_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('REPORTED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'OVERDUE', name='issue_status'), nullable=False),
    sa.Column('upvote_count', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=255), nullable=True),
    sa.Column('tracking_token', sa.String(length=64), nullable=False),
    sa.Column('contact_token', sa.String(length=64), nullable=True),
    sa.Column('sla_deadline', UTCDateTime(), nullable=False),
    sa.Column('resolved_at', UTCDateTime(), nullable=True),
    sa.Column('resolution_proof_media_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['issue_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_issues_tracking_token'), 'infrastructure_issues', ['tracking_token'], unique=True)
    op.create_table('right_of_reply',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_department', sa.String(length=255), nullable=False),
    sa.Column('author_designation', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_contact_email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'REJECTED', name='reply_status'), nullable=False),
    sa.Column('submitted_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', UTCDateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['corruption_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_right_of_reply_report_id'), 'right_of_reply', ['report_id'], unique=False)
    op.create_table('station_diary_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('COMPLAINT_RECEIVED', 'ACKNOWLEDGED', 'NCR_REGISTERED', 'FIR_REGISTERED', 'IO_ASSIGNED', 'ZERO_FIR_TRANSFERRED_OUT', 'TRANSFERRED_IN', 'CASE_DIARY', 'CHARGESHEET_FILED', 'CLOSED_WITHOUT_FIR', 'CASE_CLOSED', 'NOTE', name='diary_entry_type'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('fir_id', sa.Uuid(), nullable=True),
    sa.Column('officer_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['police_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'entry_date', 'serial_no', name='uq_gd_serial_per_station_day')
    )
    op.create_index(op.f('ix_station_diary_entries_entry_date'), 'station_diary_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_station_diary_entries_fir_id'), 'station_diary_entries', ['fir_id'], unique=False)
    op.create_index(op.f('ix_station_diary_entries_report_id'), 'station_diary_entries', ['report_id'], unique=False)
    op.create_index(op.f('ix_station_diary_entries_station_id'), 'station_diary_entries', ['station_id'], unique=False)
    op.create_table('violation_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('violation_class_id', sa.Uuid(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('camera_id', sa.String(length=100), nullable=True),
    sa.Column('location', Geometry('POINT', 4326), nullable=False),
    sa.Column('ward_id', sa.Uuid(), nullable=True),
    sa.Column('media_id', sa.String(length=255), nullable=False),
    sa.Column('identity_path', sa.Enum('ANPR', 'UNIDENTIFIED', name='case_identity_path'), nullable=False),
    sa.Column('resolved_plate_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'CONFIRMED', 'RECLASSIFIED', 'DISMISSED', name='violation_case_status'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', UTCDateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['violation_class_id'], ['violation_class_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_of_custody_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('officer_user_id', sa.Uuid(), nullable=True),
    sa.Column('case_or_fir_number', sa.String(length=100), nullable=True),
    sa.Column('accessed_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['emergency_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_of_custody_entries_report_id'), 'chain_of_custody_entries', ['report_id'], unique=False)
    op.create_table('challans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('statutory_section', sa.String(length=255), nullable=True),
    sa.Column('amount_rupees', sa.Integer(), nullable=False),
    sa.Column('due_date', UTCDateTime(), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'DISPUTED', 'UPHELD_ON_APPEAL', 'OVERTURNED_ON_APPEAL', 'PAID', name='challan_status'), nullable=False),
    sa.Column('dispute_reason', sa.String(length=1000), nullable=True),
    sa.Column('second_reviewer_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['violation_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('fir_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('fir_number', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('sections', sa.String(length=500), nullable=False),
    sa.Column('is_zero_fir', sa.Boolean(), nullable=False),
    sa.Column('transferred_to_station_id', sa.Uuid(), nullable=True),
    sa.Column('registered_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('registered_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('investigating_officer_id', sa.Uuid(), nullable=True),
    sa.Column('investigation_deadline', UTCDateTime(), nullable=False),
    sa.Column('status', sa.Enum('UNDER_INVESTIGATION', 'TRANSFERRED', 'CHARGESHEET_FILED', 'CLOSED', name='fir_status'), nullable=False),
    sa.Column('chargesheet_filed_at', UTCDateTime(), nullable=True),
    sa.Column('court_name', sa.String(length=255), nullable=True),
    sa.Column('closure_reason', sa.String(length=500), nullable=True),
    sa.Column('closed_at', UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['emergency_reports.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['police_stations.id'], ),
    sa.ForeignKeyConstraint(['transferred_to_station_id'], ['police_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id'),
    sa.UniqueConstraint('station_id', 'fir_number', name='uq_fir_number_per_station')
    )
    op.create_index(op.f('ix_fir_records_station_id'), 'fir_records', ['station_id'], unique=False)
    op.create_table('issue_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'OVERDUE', name='issue_status_history_status'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['infrastructure_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_status_history_issue_id'), 'issue_status_history', ['issue_id'], unique=False)
    op.create_table('case_diary_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fir_id', sa.Uuid(), nullable=False),
    sa.Column('officer_user_id', sa.Uuid(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fir_id'], ['fir_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_diary_entries_fir_id'), 'case_diary_entries', ['fir_id'], unique=False)
    # ### end Alembic commands ###

    for table in APPEND_ONLY_TABLES:
        # Two triggers, because MySQL has no "BEFORE UPDATE OR DELETE" form. The message matches
        # the PostgreSQL wording this schema replaced, so the smoke test reads the same on both.
        op.execute(
            f"CREATE TRIGGER {table}_no_update BEFORE UPDATE ON {table} FOR EACH ROW "
            f"SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "
            f"'Table {table} is append-only: UPDATE is not permitted'"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table} FOR EACH ROW "
            f"SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "
            f"'Table {table} is append-only: DELETE is not permitted'"
        )

    # A report sealed as restricted can never be unsealed. This is the one flag in the system
    # whose flip would expose sexual-offence and minor-related evidence to the ordinary queues,
    # so it is enforced by the database rather than by whoever writes the next endpoint.
    op.execute(
        "CREATE TRIGGER emergency_reports_no_unrestrict BEFORE UPDATE ON emergency_reports "
        "FOR EACH ROW IF OLD.is_restricted = 1 AND NEW.is_restricted = 0 THEN "
        "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "
        "'A restricted emergency report can never be made unrestricted'; END IF"
    )

    for name, table, column in SPATIAL_INDEXES:
        op.execute(f"CREATE SPATIAL INDEX {name} ON {table} ({column})")


def downgrade() -> None:
    """
    Drop everything this migration created.

    Written by hand rather than left as Alembic's reversed create_table list, because that list
    does not survive MySQL. Two reasons: an index backing a foreign key cannot be dropped while
    the constraint still references it, so the generated `drop_index` calls fail; and MySQL has
    no transactional DDL, so a downgrade that fails halfway leaves a partly-dropped schema that
    the next attempt then trips over.

    Turning off foreign key checks for the duration makes the drop order irrelevant, which is
    what makes this safe to re-run after a failure.
    """
    op.execute("DROP TRIGGER IF EXISTS emergency_reports_no_unrestrict")
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_update")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_delete")

    # Spatial indexes go with their tables; naming them here would only add another statement
    # that can fail on a re-run.
    op.execute("SET FOREIGN_KEY_CHECKS = 0")
    try:
        for table in reversed(sa.inspect(op.get_bind()).get_table_names()):
            if table != "alembic_version":
                op.execute(f"DROP TABLE IF EXISTS `{table}`")
    finally:
        op.execute("SET FOREIGN_KEY_CHECKS = 1")
