"""module 4 stations, report lifecycle and chain of custody fields

Revision ID: 97428024586f
Revises: 3fabf2cb5577
Create Date: 2026-09-20 14:43:09.312946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '97428024586f'
down_revision: Union[str, None] = '3fabf2cb5577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('police_stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('chain_of_custody_entries', sa.Column('action', sa.String(length=50), nullable=False))
    op.add_column('chain_of_custody_entries', sa.Column('detail', sa.String(length=500), nullable=True))
    op.alter_column('chain_of_custody_entries', 'officer_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chain_of_custody_entries', 'case_or_fir_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('emergency_reports', sa.Column('media_id', sa.String(length=255), nullable=True))
    op.add_column('emergency_reports', sa.Column('ward_id', sa.UUID(), nullable=True))
    op.add_column('emergency_reports', sa.Column('station_id', sa.UUID(), nullable=True))
    op.add_column('emergency_reports', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('emergency_reports', sa.Column('fir_number', sa.String(length=100), nullable=True))
    op.add_column('emergency_reports', sa.Column('fir_registered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('emergency_reports', sa.Column('closed_without_fir_reason', sa.String(length=500), nullable=True))
    op.add_column('emergency_reports', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('emergency_reports', 'original_sha256',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # Named explicitly: autogenerate emits None here, and the downgrade then cannot drop it.
    op.create_foreign_key(
        'fk_emergency_reports_station_id', 'emergency_reports', 'police_stations', ['station_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_emergency_reports_station_id', 'emergency_reports', type_='foreignkey')

    # Reports filed without an evidence file, and the intake entries written before any officer
    # touches them, only exist under the new schema - the old one had no way to represent them.
    # Without clearing them first the NOT NULL restorations below fail and the downgrade cannot
    # run at all. Losing those rows is the accepted cost of reversing a schema in development.
    #
    # The append-only trigger refuses this DELETE, which is the trigger doing its job, so it is
    # lifted for exactly this statement and restored immediately. Nothing in the application can
    # do this: it needs table ownership, and it lives in a migration where it is reviewable.
    op.execute("ALTER TABLE chain_of_custody_entries DISABLE TRIGGER chain_of_custody_entries_append_only")
    op.execute(
        """
        DELETE FROM chain_of_custody_entries
        WHERE officer_user_id IS NULL
           OR case_or_fir_number IS NULL
           OR report_id IN (SELECT id FROM emergency_reports WHERE original_sha256 IS NULL)
        """
    )
    op.execute("ALTER TABLE chain_of_custody_entries ENABLE TRIGGER chain_of_custody_entries_append_only")
    op.execute("DELETE FROM emergency_reports WHERE original_sha256 IS NULL")

    op.alter_column('emergency_reports', 'original_sha256',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('emergency_reports', 'closed_at')
    op.drop_column('emergency_reports', 'closed_without_fir_reason')
    op.drop_column('emergency_reports', 'fir_registered_at')
    op.drop_column('emergency_reports', 'fir_number')
    op.drop_column('emergency_reports', 'acknowledged_at')
    op.drop_column('emergency_reports', 'station_id')
    op.drop_column('emergency_reports', 'ward_id')
    op.drop_column('emergency_reports', 'media_id')
    op.alter_column('chain_of_custody_entries', 'case_or_fir_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('chain_of_custody_entries', 'officer_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('chain_of_custody_entries', 'detail')
    op.drop_column('chain_of_custody_entries', 'action')
    op.drop_table('police_stations')
    # ### end Alembic commands ###
