"""initial schema: shared plumbing plus modules 1-4

Revision ID: a1d2e31c29b2
Revises: 
Create Date: 2026-09-19 17:33:47.478883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

revision: str = 'a1d2e31c29b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('VIEW', 'CONFIRM', 'RECLASSIFY', 'DISMISS', 'UNBLUR_TOGGLE', 'CHALLAN_ISSUED', 'STATUS_CHANGE', 'LOGIN', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_table('corruption_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accused_department', sa.String(length=255), nullable=False),
    sa.Column('accused_designation', sa.String(length=255), nullable=False),
    sa.Column('accused_party_type', sa.Enum('STATE_GOVT_EMPLOYEE', 'CENTRAL_GOVT_EMPLOYEE', 'POLICE_PERSONNEL', 'MUNICIPAL_OR_DEPT_STAFF', name='corruption_accused_party_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geohash', sa.String(length=20), nullable=False),
    sa.Column('media_id', sa.String(length=255), nullable=False),
    sa.Column('moderation_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='moderation_status'), nullable=False),
    sa.Column('public_status_badge', sa.Enum('UNVERIFIED_ALLEGATION', 'UNDER_INVESTIGATION', 'ACTION_TAKEN', 'DISMISSED', name='public_status_badge'), nullable=False),
    sa.Column('tracking_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corruption_reports_tracking_token'), 'corruption_reports', ['tracking_token'], unique=True)
    op.create_table('corruption_routing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accused_party_type', sa.Enum('STATE_GOVT_EMPLOYEE', 'CENTRAL_GOVT_EMPLOYEE', 'POLICE_PERSONNEL', 'MUNICIPAL_OR_DEPT_STAFF', name='accused_party_type'), nullable=False),
    sa.Column('primary_route_body', sa.String(length=255), nullable=False),
    sa.Column('notify_local_police', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accused_party_type')
    )
    op.create_table('emergency_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ASSAULT_IN_PROGRESS', 'HOMICIDE_OR_BODY_DISCOVERED', 'SEXUAL_OFFENCE_ADULT', 'MINOR_INVOLVED', 'NARCOTICS', 'HUMAN_TRAFFICKING', name='emergency_report_category'), nullable=False),
    sa.Column('original_sha256', sa.String(length=64), nullable=False),
    sa.Column('geohash', sa.String(length=20), nullable=False),
    sa.Column('tracking_token', sa.String(length=64), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_reports_tracking_token'), 'emergency_reports', ['tracking_token'], unique=True)
    op.create_table('emergency_routing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('ASSAULT_IN_PROGRESS', 'HOMICIDE_OR_BODY_DISCOVERED', 'SEXUAL_OFFENCE_ADULT', 'MINOR_INVOLVED', 'NARCOTICS', 'HUMAN_TRAFFICKING', name='offence_category'), nullable=False),
    sa.Column('alert_routed_to', sa.String(length=500), nullable=False),
    sa.Column('has_public_record', sa.Boolean(), nullable=False),
    sa.Column('is_hard_stop', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('issue_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('escalation_department', sa.String(length=255), nullable=False),
    sa.Column('escalation_department_tier2', sa.String(length=255), nullable=True),
    sa.Column('duplicate_radius_meters', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('issue_contact_phones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_token', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_contact_phones_contact_token'), 'issue_contact_phones', ['contact_token'], unique=True)
    op.create_table('responsible_desks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('municipal_zone', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('grievance_api_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synthetic_vehicle_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthetic_vehicle_registry_plate_number'), 'synthetic_vehicle_registry', ['plate_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MUNICIPAL_OFFICER', 'VIGILANCE_OFFICER', 'MODERATOR', 'DEPARTMENT_ENGINEER', 'INVESTIGATING_OFFICER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('jurisdiction_ward_id', sa.UUID(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('violation_class_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('identity_path', sa.Enum('ANPR', 'UNIDENTIFIED', name='identity_path'), nullable=False),
    sa.Column('statutory_section', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_geospatial_table('wards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ward_number', sa.String(length=50), nullable=False),
    sa.Column('municipal_zone', sa.String(length=255), nullable=False),
    sa.Column('assembly_constituency', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('boundary', Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_wards_boundary', 'wards', ['boundary'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('chain_of_custody_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('officer_user_id', sa.UUID(), nullable=False),
    sa.Column('case_or_fir_number', sa.String(length=100), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['emergency_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chain_of_custody_entries_report_id'), 'chain_of_custody_entries', ['report_id'], unique=False)
    op.create_table('fine_ladder_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('violation_class_id', sa.UUID(), nullable=False),
    sa.Column('occurrence_number', sa.Integer(), nullable=False),
    sa.Column('amount_rupees', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['violation_class_id'], ['violation_class_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_table('infrastructure_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('REPORTED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'OVERDUE', name='issue_status'), nullable=False),
    sa.Column('upvote_count', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=255), nullable=True),
    sa.Column('tracking_token', sa.String(length=64), nullable=False),
    sa.Column('contact_token', sa.String(length=64), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_proof_media_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['issue_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_infrastructure_issues_location', 'infrastructure_issues', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_infrastructure_issues_tracking_token'), 'infrastructure_issues', ['tracking_token'], unique=True)
    op.create_geospatial_table('violation_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('violation_class_id', sa.UUID(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('camera_id', sa.String(length=100), nullable=True),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('media_id', sa.String(length=255), nullable=False),
    sa.Column('identity_path', sa.Enum('ANPR', 'UNIDENTIFIED', name='case_identity_path'), nullable=False),
    sa.Column('resolved_plate_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'CONFIRMED', 'RECLASSIFIED', 'DISMISSED', name='violation_case_status'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['violation_class_id'], ['violation_class_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_violation_cases_location', 'violation_cases', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('challans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('statutory_section', sa.String(length=255), nullable=True),
    sa.Column('amount_rupees', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'DISPUTED', 'UPHELD_ON_APPEAL', 'OVERTURNED_ON_APPEAL', 'PAID', name='challan_status'), nullable=False),
    sa.Column('dispute_reason', sa.String(length=1000), nullable=True),
    sa.Column('second_reviewer_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['violation_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('issue_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'OVERDUE', name='issue_status_history_status'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['infrastructure_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_status_history_issue_id'), 'issue_status_history', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_status_history_issue_id'), table_name='issue_status_history')
    op.drop_table('issue_status_history')
    op.drop_table('challans')
    op.drop_geospatial_index('idx_violation_cases_location', table_name='violation_cases', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('violation_cases')
    op.drop_index(op.f('ix_infrastructure_issues_tracking_token'), table_name='infrastructure_issues')
    op.drop_geospatial_index('idx_infrastructure_issues_location', table_name='infrastructure_issues', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('infrastructure_issues')
    op.drop_table('fine_ladder_configs')
    op.drop_index(op.f('ix_chain_of_custody_entries_report_id'), table_name='chain_of_custody_entries')
    op.drop_table('chain_of_custody_entries')
    op.drop_geospatial_index('idx_wards_boundary', table_name='wards', postgresql_using='gist', column_name='boundary')
    op.drop_geospatial_table('wards')
    op.drop_table('violation_class_configs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_synthetic_vehicle_registry_plate_number'), table_name='synthetic_vehicle_registry')
    op.drop_table('synthetic_vehicle_registry')
    op.drop_table('responsible_desks')
    op.drop_index(op.f('ix_issue_contact_phones_contact_token'), table_name='issue_contact_phones')
    op.drop_table('issue_contact_phones')
    op.drop_table('issue_categories')
    op.drop_table('emergency_routing_rules')
    op.drop_index(op.f('ix_emergency_reports_tracking_token'), table_name='emergency_reports')
    op.drop_table('emergency_reports')
    op.drop_table('corruption_routing_rules')
    op.drop_index(op.f('ix_corruption_reports_tracking_token'), table_name='corruption_reports')
    op.drop_table('corruption_reports')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###

    # Alembic's autogenerated downgrade drops tables but leaves the ENUM types behind, so a
    # downgrade-then-upgrade cycle fails with "type ... already exists". Added by hand.
    for enum_name in (
        'accused_party_type',
        'audit_action',
        'case_identity_path',
        'challan_status',
        'corruption_accused_party_type',
        'emergency_report_category',
        'identity_path',
        'issue_status',
        'issue_status_history_status',
        'moderation_status',
        'offence_category',
        'public_status_badge',
        'user_role',
        'violation_case_status',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
