"""police station network, general diary, FIR register and case diary

Revision ID: b489707d2370
Revises: 97428024586f
Create Date: 2026-09-22 20:48:55.404474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

revision: str = 'b489707d2370'
down_revision: Union[str, None] = '97428024586f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_diary_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('COMPLAINT_RECEIVED', 'ACKNOWLEDGED', 'NCR_REGISTERED', 'FIR_REGISTERED', 'IO_ASSIGNED', 'ZERO_FIR_TRANSFERRED_OUT', 'TRANSFERRED_IN', 'CASE_DIARY', 'CHARGESHEET_FILED', 'CLOSED_WITHOUT_FIR', 'CASE_CLOSED', 'NOTE', name='diary_entry_type'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('fir_id', sa.UUID(), nullable=True),
    sa.Column('officer_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['police_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'entry_date', 'serial_no', name='uq_gd_serial_per_station_day')
    )
    op.create_index(op.f('ix_station_diary_entries_entry_date'), 'station_diary_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_station_diary_entries_fir_id'), 'station_diary_entries', ['fir_id'], unique=False)
    op.create_index(op.f('ix_station_diary_entries_report_id'), 'station_diary_entries', ['report_id'], unique=False)
    op.create_index(op.f('ix_station_diary_entries_station_id'), 'station_diary_entries', ['station_id'], unique=False)
    op.create_table('fir_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('fir_number', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('sections', sa.String(length=500), nullable=False),
    sa.Column('is_zero_fir', sa.Boolean(), nullable=False),
    sa.Column('transferred_to_station_id', sa.UUID(), nullable=True),
    sa.Column('registered_by_user_id', sa.UUID(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('investigating_officer_id', sa.UUID(), nullable=True),
    sa.Column('investigation_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('UNDER_INVESTIGATION', 'TRANSFERRED', 'CHARGESHEET_FILED', 'CLOSED', name='fir_status'), nullable=False),
    sa.Column('chargesheet_filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('court_name', sa.String(length=255), nullable=True),
    sa.Column('closure_reason', sa.String(length=500), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['emergency_reports.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['police_stations.id'], ),
    sa.ForeignKeyConstraint(['transferred_to_station_id'], ['police_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id'),
    sa.UniqueConstraint('station_id', 'fir_number', name='uq_fir_number_per_station')
    )
    op.create_index(op.f('ix_fir_records_station_id'), 'fir_records', ['station_id'], unique=False)
    op.create_table('case_diary_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fir_id', sa.UUID(), nullable=False),
    sa.Column('officer_user_id', sa.UUID(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fir_id'], ['fir_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_diary_entries_fir_id'), 'case_diary_entries', ['fir_id'], unique=False)
    op.drop_column('emergency_reports', 'fir_registered_at')
    op.drop_column('emergency_reports', 'fir_number')
    op.add_column('police_stations', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_geospatial_column('police_stations', sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('police_stations', sa.Column('sho_name', sa.String(length=255), nullable=True))
    op.add_column(
        'police_stations',
        # server_default backfills the stations already in the table; the application sets it
        # explicitly from here on.
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.create_geospatial_index('idx_police_stations_location', 'police_stations', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.add_column('users', sa.Column('police_station_id', sa.UUID(), nullable=True))

    # The General Diary and the case diary are bound registers in a real station: entries are
    # added, never altered. reject_mutation() is the same guard the audit log and chain of
    # custody use (migration 3fabf2cb5577).
    for table in ("station_diary_entries", "case_diary_entries"):
        op.execute(
            f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION reject_mutation();
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER {table}_no_truncate
            BEFORE TRUNCATE ON {table}
            FOR EACH STATEMENT EXECUTE FUNCTION reject_mutation();
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ("station_diary_entries", "case_diary_entries"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
        op.execute(f"DROP TRIGGER IF EXISTS {table}_no_truncate ON {table}")

    op.drop_column('users', 'police_station_id')
    op.drop_geospatial_index('idx_police_stations_location', table_name='police_stations', postgresql_using='gist', column_name='location')
    op.drop_column('police_stations', 'is_active')
    op.drop_column('police_stations', 'sho_name')
    op.drop_geospatial_column('police_stations', 'location')
    op.drop_column('police_stations', 'address')
    op.add_column('emergency_reports', sa.Column('fir_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('emergency_reports', sa.Column('fir_registered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_case_diary_entries_fir_id'), table_name='case_diary_entries')
    op.drop_table('case_diary_entries')
    op.drop_index(op.f('ix_fir_records_station_id'), table_name='fir_records')
    op.drop_table('fir_records')
    op.drop_index(op.f('ix_station_diary_entries_station_id'), table_name='station_diary_entries')
    op.drop_index(op.f('ix_station_diary_entries_report_id'), table_name='station_diary_entries')
    op.drop_index(op.f('ix_station_diary_entries_fir_id'), table_name='station_diary_entries')
    op.drop_index(op.f('ix_station_diary_entries_entry_date'), table_name='station_diary_entries')
    op.drop_table('station_diary_entries')
    # ### end Alembic commands ###
